### ISSUE TITLE
Add "Alert Conditions" as an entity type to Tag Improver

### ISSUE THREAD

**Issue by spandanak25** [newrelic/nr1-tag-improver#114]
Summary: 
Working on a project to identify required tags for all alert conditions in different NR accounts. The tag improver will be great to use if "Alert conditions" can be added to the entities. That way, I will be able to use the tag improver to check if the certain tags I'm looking for are added to all alert conditions in NR and which ones aren't.

**Comment by shahramk** [comment]
@spandanak25, an entity type for alert conditions was added to tag improver (new version 1.4.0).
In tag improver, please select "Alert Conditions" from entity type pulldown menu on the top right hand corner of the page to get the tags and entities for alerts.
