### ISSUE TITLE
Ability to tag alert conditions using tag improver

### ISSUE THREAD

**Issue by evanhaxton** [newrelic/nr1-tag-improver#127]
## Summary

 There is no ability to access nor tag alert conditions within the tool. 

## Desired Behaviour

It would be great to be able to tag alert conditions.  As an example, alert conditions have only Critical and Warning levels assigned to the condition.  Ideally, it would be helpful if tags could be added to better describe the issue such as P1 thru P5 as an example.

## Possible Solution

We are simply looking for the alert condition to be treated the same as any other entity.  This capability would be able to support all alert conditions that include infrastructure and nrql based alerts

## Additional context

If the customer is using downstream tools, additional context is always valuable in these circumstances

**Comment by shahramk** [comment]
@evanhaxton which version of tag improver are you using and in what region (EU / US)?
The alert condition entities where added in the last version of the nerdlet and deployed to the platform on Feb 2 2023
