### ISSUE TITLE
Workflow from Tag Analyzer to see "which entities are using this key:value"

### ISSUE THREAD

**Issue by fightingmonk** [newrelic/nr1-tag-improver#50]
When viewing the Tag analyzer, a user wants to know "which entities are using this specific tag key:value that I see?"

A solution would be to switch over to the Entities view and filter the entity list to the relevant key:value.

UX solution for this should also address #51

2020/03/24 Update: Add new radio button in Entities for:
"All entities with this tag defined with `<value>` value" <- is selectable, prepopulated if Entities is opened from "manage" in Tag Analyzer

**Comment by shahramk** [comment]
a tag value dropdown was added to the Entity tab to allow filtering by specific tag key:value.
commit: feat: v1.1-tag-analyzer-links - filter entities by selected tag key/value
