### ISSUE TITLE
Bulk add & rename tag key pickers include policy tags that have not been applied yet

### ISSUE THREAD

**Issue by fightingmonk** [newrelic/nr1-tag-improver#52]
As a user, if I try to add or rename a tag, include tag keys from the policy schema that are not present on existing entities. This will eliminate typing and capitalization/spelling/formatting errors during data entry when I am trying to add a required or optional tag that has not yet been populated.

**Comment by shahramk** [comment]
tagHierarchy is updated when the policy updated and tags are added/removed.
commit: fix: v1.1-tag-analyzer-links - update tags in tagHierarchy when policy changed
