### ISSUE TITLE
Improve discoverability in Entities view

### ISSUE THREAD

**Issue by fightingmonk** [newrelic/nr1-tag-improver#53]
Based on initial user feedback, a couple of issues we should address:
* Show all policy tags function is not discoverable; would prefer to default to showing all policy tags and having option to hide the in-compliance tags.
* "How do I sort and filter the Entities table to only the things I want to edit"; maybe solved by #50 and #51? Maybe remove "show values for this tag in the table" and instead implement a search filter that scans entity name, tag key & value?

**Comment by shahramk** [comment]
- bullet 1 - changed the default to show all tags for the entity
- bullet 2 - fixed in #50 and #51
