### ISSUE TITLE
Coverage % is incorrect

### ISSUE THREAD

**Issue by danifitz** [newrelic/nr1-tag-improver#56]
## Description

Working with the app, we have created some policies. The coverage % is way off.

![image](https://user-images.githubusercontent.com/3629903/107213440-53003980-6a00-11eb-9458-19e7be327cc3.png)

## Steps to Reproduce

Defined a custom policy with required status. 

## Expected Behaviour

Coverage % should be below or equal to 100%

## Relevant Logs / Console output

N/A

**Comment by jpconway** [comment]
Fixed in version 1.0.6

**Comment by shahramk** [comment]
this issue was not reproducible. an update in v1.0.5 fixed this issue on 1-13.
