### ISSUE TITLE
Show tag type in Tag Analyzer

### ISSUE THREAD

**Issue by jpconway** [newrelic/nr1-tag-improver#62]
Include new column in Tag Analyzer to indicate whether a tag is Required, Optional, or Non-Policy

## Summary
As an admin user, when analyzing tag coverage and usage for an account, I want to see what the tag type is for each tag listed so that I can better prioritize my tag management actions and audit non-policy tags.
## Desired Behaviour
Tag Analyzer should include a new column with icon indicator to indicate whether tag is Required, Optional, or Non-Policy according to the tag policy in place, with default sort order: Required, Optional, Non-Policy

## Possible Solution
New Tag Analyzer column listing: Tag Name, Enforcement Level, Distinct Values, Tagged Entities, % Coverage

## Additional context
mockup: https://whimsical.com/taganalyzer-withenforcementlevelcol-7V6P3rZ8q5DXohp5FS6tEM

**Comment by shahramk** [comment]
a column was added to show tag enforcement level.
the tags key dropdown works the same way.
tags are sorted in order of "required", "optional", "non-policy", alphabetically within their sections.

commit:  #62: show enforcement level in tag view + add sorting for tags and dropdown by required, optional, non-policy
