### ISSUE TITLE
Consolidate tag key:value filtering in Entities tab

### ISSUE THREAD

**Issue by jpconway** [newrelic/nr1-tag-improver#68]
## Summary
We need to consolidate the filtering options in the Entities tab to provide a more consistent and improved user experience
## Desired Behaviour
Users should be able to easily filter entities shown in the Entities tab to only those entities that have a specific tag key:value  set.  This should include filtering to only entities where there is _any_ value for a tag, or _no_ value for a tag, indicating that the tag is not defined or present for the entity.
## Possible Solution
- Remove all radio button filtering and "Show values for this tag in the table:`tag`"
- Replace with "Show all entities where `tag` has `value` defined"
   - `tag` is the common policy tag dropdown, showing only those tags in policy and organized by enforcement level
   - `value` is a dropdown of all values present in the account scope.
      - The `values` list should indicate which values valid/in compliance if the tag has a `closed` license definition separate from values that are present but non-compliant with the valid tag values according to the policy.

**Comment by shahramk** [comment]
consolidated all entity view filtering into the tag value dropdown. it allows to view entities for a tag by the following:
- \<any tag value\>
- \<tag not defined\>
- \<show all entities\>
- and list of all specific tag values for the currently selected tag
