### ISSUE TITLE
Tag Analyzer: Indicate selected tag in Tags In Use pane when tag selected in Breakdown pane

### ISSUE THREAD

**Issue by jpconway** [newrelic/nr1-tag-improver#69]
## Summary
Tag Analyzer needs to reflect the tag selected by users in the "Values Breakdown" pane in the "Tags in use" pane as well
## Desired Behaviour
When a user selects a tag in the "Values Breakdown" list, the corresponding row for that tag in the "Tags in use" pane should change to indicate that it is now the tag in focus.
## Possible Solution
The entire row for a selected tag should change color (to indicate current focus) and remain that color until a new tag is selected.  This behavior should be the same whether tag is selected by clicking on a row in the table of tags in the "Tags in use" pane, or selecting a tag from the dropdown list in the "Values Breakdown" pane.

**Comment by shahramk** [comment]
the table on the left and the dropdown on the right side of Tag Analyzer tab are now synchronized.

commit: feat: v1.1-tag-analyzer-links - change selected row's background color
