### ISSUE TITLE
Tag dropdown lists in Actions (Add/Change/Rename/Remove) in Entities tab should be consistent with other Tag dropdown lists

### ISSUE THREAD

**Issue by jpconway** [newrelic/nr1-tag-improver#70]
## Summary
The dropdown lists for tags in the "Add Tags", "Rename Tags", "Change Values", and "Remove Tags" should be consistent with the tag dropdown lists used elsewhere in Tag Improver and reflect the enforcement levels and valid values of the tags.

## Desired Behaviour
In "Add Tags", "Change Values", and "Remove Tags", the dropdown list for `Tag key` should indicate enforcement levels and organize by Required or Optional.
In "Rename Tags", the dropdown list for `Tag key` should indicate enforcement levels and organize by Required or Optional, **but also display all Non-Policy tags**.

In "Add Tags" and "Change Values", the dropdown list for `Tag value` should be restricted to only those valid values if the selected tag has a `Closed` license with a specific set of valid values.

**Comment by shahramk** [comment]
The fields in bulk-editing functions are auto-complete text boxes and do not have the same capabilities as dropdown components.

**Comment by jpconway** [comment]
Duplicate of #63
